export type LoyaltyTier = "bronze" | "silver" | "gold";
/**
 * A pack size, as the operator typed it: "200g", "250g", "12oz", "Sample".
 *
 * Was an enum of exactly three values, in the database as well as here, which
 * made adding a size a code change and a deployment. Ordering comes from
 * weight_grams instead, which is more correct anyway -- it puts a new 250g
 * between 200g and 1kg with nobody maintaining a list.
 */
export type VariantSize = string;
export type OrderStatus =
  | "pending"
  | "paid"
  | "roasting"
  | "shipped"
  | "completed"
  | "cancelled";
export type RoastingStatus = "new" | "quoted" | "accepted" | "declined" | "done";
export type PostStatus = "draft" | "scheduled" | "published";
/**
 * Where a sale came from.
 *
 * Text in the database rather than an enum, for the same reason VariantSize
 * is: adding "tokopedia" next year should be one line, not a migration and a
 * deployment. Anything other than "online" was entered by hand.
 */
export type SalesChannel =
  | "online"
  | "pos"
  | "whatsapp"
  | "instagram"
  | "marketplace"
  | "other";

/** Offered as a starting point in the admin, not a limit. */
export const SUGGESTED_SIZES = ["100g", "200g", "250g", "500g", "1kg"];

export const ORDER_STATUSES: OrderStatus[] = [
  "pending",
  "paid",
  "roasting",
  "shipped",
  "completed",
  "cancelled",
];

/** Channels an order can be written by hand into. "online" is not one of
 *  them -- those are written by the checkout. */
export const MANUAL_CHANNELS: SalesChannel[] = [
  "pos",
  "whatsapp",
  "instagram",
  "marketplace",
  "other",
];

export const CHANNEL_LABELS: Record<SalesChannel, string> = {
  online: "Website",
  pos: "Shop counter",
  whatsapp: "WhatsApp",
  instagram: "Instagram",
  marketplace: "Marketplace",
  other: "Somewhere else",
};

/** What to call the thread an order came from, per channel. Shown as the
 *  field's label so the operator is never guessing what to type in it. */
export const CHANNEL_REFERENCE_LABELS: Partial<Record<SalesChannel, string>> = {
  whatsapp: "WhatsApp number",
  instagram: "Instagram handle",
  marketplace: "Marketplace order number",
  other: "Where it came from",
};

export const ROASTING_STATUSES: RoastingStatus[] = [
  "new",
  "quoted",
  "accepted",
  "declined",
  "done",
];

export interface Profile {
  id: string;
  display_name: string | null;
  email: string | null;
  phone: string | null;
  loyalty_points: number;
  lifetime_points: number;
  tier: LoyaltyTier;
  is_admin: boolean;
  created_at: string;
}

export interface Address {
  id: string;
  user_id: string;
  recipient_name: string;
  phone: string;
  line1: string;
  line2: string | null;
  /** Kelurahan or desa. */
  village: string | null;
  /** Kecamatan. */
  district: string | null;
  city: string;
  province: string | null;
  postal_code: string | null;
  country: string;
  /** Biteship's key for this place, when it came from the area lookup. */
  area_id: string | null;
  is_default: boolean;
  created_at: string;
}

export interface Category {
  id: string;
  slug: string;
  name: string;
  description: string | null;
  image_url: string | null;
  show_on_homepage: boolean;
  sort_order: number;
  seo_title: string | null;
  seo_description: string | null;
}

export interface ProductVariant {
  id: string;
  product_id: string;
  size: VariantSize;
  /** Bags physically on the shelf. */
  stock: number;
  /** Of those bags, how many an agreed-but-unpaid manual order is holding. */
  reserved: number;
  /**
   * What may still be sold: stock minus reserved, never below zero.
   *
   * Generated by the database, so it cannot be written and cannot disagree
   * with its two inputs. Every "can I sell this" check reads this column --
   * the shop, the till, and the checkout API alike.
   */
  available: number;
  price_idr: number;
  weight_grams: number;
  is_active: boolean;
}

export interface Product {
  id: string;
  slug: string;
  name: string;
  description: string | null;
  origin: string | null;
  process: string | null;
  roast_level: string | null;
  varietal: string | null;
  masl: string | null;
  tasting_notes: string | null;
  category_id: string | null;
  image_url: string | null;
  image_alt: string | null;
  /** Publish flavour scale, 1–6. Null until assigned. See lib/flavour.ts. */
  flavour_level: number | null;
  is_active: boolean;
  is_featured: boolean;
  sort_order: number;
  seo_title: string | null;
  seo_description: string | null;
  og_image_url: string | null;
  created_at: string;
  updated_at: string;
}

export interface ProductWithVariants extends Product {
  product_variants: ProductVariant[];
  categories?: Pick<Category, "id" | "slug" | "name"> | null;
}

export interface OrderItem {
  id: string;
  order_id: string;
  product_id: string | null;
  variant_id: string | null;
  name_snapshot: string;
  size_snapshot: string;
  slug_snapshot: string | null;
  unit_price_idr: number;
  quantity: number;
}

/**
 * The address an order is going to, copied onto the order at the time.
 *
 * A snapshot rather than a reference: a customer who edits their saved address
 * next year must not silently rewrite where last year's parcel went.
 *
 * `village` and `district` are the two levels an Indonesian address has that
 * the generic western set leaves out — kelurahan and kecamatan. `area_id` is
 * Biteship's key for the place, present when the address was picked from the
 * lookup rather than typed, and what makes an accurate rate (and a real
 * courier booking) possible.
 *
 * All three are optional: addresses recorded before the lookup existed are
 * still perfectly good addresses.
 */
export interface ShippingAddressSnapshot {
  recipient_name: string;
  phone: string;
  email?: string | null;
  line1: string;
  line2?: string | null;
  /** Kelurahan or desa. */
  village?: string | null;
  /** Kecamatan. */
  district?: string | null;
  city: string;
  province?: string | null;
  postal_code?: string | null;
  country: string;
  area_id?: string | null;
}

/**
 * Whether an address has enough on it to put a parcel in the post.
 *
 * Deliberately not enforced when an order is *saved*. An order agreed over
 * WhatsApp often arrives before the address does — "I'll send it later" — and
 * refusing to record the order until then means it lives in the chat instead
 * of in the shop's books, which is the thing all of this exists to stop.
 *
 * It is enforced at the point it actually matters: a tracking number means a
 * parcel has gone somewhere, and it cannot have gone to half an address.
 */
export function addressIsComplete(
  address: ShippingAddressSnapshot | null | undefined,
): boolean {
  if (!address) return false;
  return Boolean(
    address.recipient_name?.trim() &&
      address.phone?.trim() &&
      address.line1?.trim() &&
      address.city?.trim(),
  );
}

export interface Order {
  id: string;
  human_ref: string;
  /** Where the sale happened. Counter sales carry no address or shipping. */
  channel: SalesChannel;
  /** The thread this order came from: a phone number, an @handle, a
   *  marketplace reference. Null for website orders. */
  channel_reference: string | null;
  /** Set while this order is holding stock it has not yet paid for. Cleared
   *  when it settles or is cancelled. */
  stock_reserved_at: string | null;
  cash_received_idr: number | null;
  staff_id: string | null;
  user_id: string | null;
  guest_email: string | null;
  status: OrderStatus;
  subtotal_idr: number;
  /** What the customer was charged for shipping. */
  shipping_idr: number;
  /** What the roastery absorbed on this order's shipping. */
  shipping_discount_idr: number;
  /** Taken off the coffee — kept apart from shipping_discount_idr so the two
   *  never have to be untangled afterwards. */
  discount_idr: number;
  discount_reason: string | null;
  unique_code: number;
  total_idr: number;
  payment_method: string | null;
  payment_ref: string | null;
  payment_url: string | null;
  payment_expires_at: string | null;
  shipping_address: ShippingAddressSnapshot | null;
  shipping_zone: string | null;
  courier_note: string | null;
  tracking_number: string | null;
  customer_note: string | null;
  points_awarded: number;
  /** Courier-side identifiers, populated by courier webhooks. */
  courier_order_id: string | null;
  courier_tracking_id: string | null;
  courier_waybill_id: string | null;
  courier_company: string | null;
  courier_type: string | null;
  courier_status: string | null;
  courier_driver_name: string | null;
  courier_driver_phone: string | null;
  /** What the courier actually charged, which can exceed what the customer
   *  paid when real weight differs from quoted weight. */
  courier_charged_idr: number | null;
  /** Set once the receipt has been sent, so a redelivered payment webhook
   *  cannot send a second one. */
  confirmation_email_sent_at: string | null;
  /** The tracking number the customer was last emailed. */
  shipped_email_tracking: string | null;
  created_at: string;
  paid_at: string | null;
  /** When the parcel actually left. Stamped the first time an order is marked
   *  shipped, and correctable afterwards — a parcel is often posted a day
   *  before anyone gets round to updating the site. */
  shipped_at: string | null;
  /** Set when an order was undone as a mistake. A voided order keeps its row
   *  but is excluded from every report, list and total. */
  voided_at: string | null;
  voided_reason: string | null;
  voided_by: string | null;
  /** Whether it was holding reserved stock when voided, so restoring knows to
   *  put the hold back. */
  voided_held_stock: boolean;
  /** Do not ship before this date. An order carrying one is a scheduled
   *  order (a "PO"); nothing else about it is different. */
  ship_after: string | null;
  /** The bucket this order's points went into, when there was no account to
   *  award them to. */
  pending_loyalty_id: string | null;
}

/**
 * Loyalty points earned by someone who had no account at the time.
 *
 * Keyed on a contact detail rather than a person, because `profiles` needs an
 * `auth.users` row behind it and these people have not signed up yet.
 */
export interface PendingLoyalty {
  id: string;
  kind: "email" | "phone";
  identifier: string;
  points: number;
  lifetime_points: number;
  order_count: number;
  first_seen_at: string;
  last_seen_at: string;
  claimed_by: string | null;
  claimed_at: string | null;
}

export interface OrderWithItems extends Order {
  order_items: OrderItem[];
}

export interface RoastingRequest {
  id: string;
  human_ref: string;
  user_id: string | null;
  contact_name: string;
  contact_phone: string;
  email: string | null;
  green_bean_origin: string;
  quantity_kg: number;
  desired_roast_level: string | null;
  notes: string | null;
  status: RoastingStatus;
  quoted_price_idr: number | null;
  admin_note: string | null;
  created_at: string;
  updated_at: string;
}

export interface BlogCategory {
  id: string;
  slug: string;
  name: string;
  description: string | null;
  accent_color: string;
  sort_order: number;
}

export interface BlogPost {
  id: string;
  slug: string;
  title: string;
  excerpt: string | null;
  body: string | null;
  cover_image: string | null;
  cover_alt: string | null;
  author_name: string;
  blog_category_id: string | null;
  tags: string[];
  status: PostStatus;
  is_featured: boolean;
  reading_minutes: number | null;
  seo_title: string | null;
  seo_description: string | null;
  og_image_url: string | null;
  published_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface BlogPostWithCategory extends BlogPost {
  blog_categories?: Pick<BlogCategory, "id" | "slug" | "name" | "accent_color"> | null;
}

export interface ShippingZone {
  id: string;
  code: string;
  name: string;
  country_codes: string[];
  is_domestic: boolean;
  base_rate_idr: number;
  threshold_grams: number;
  heavy_rate_idr: number;
  free_shipping_over_idr: number | null;
  /** Spend at or above this for a partial subsidy. Null disables it. */
  subsidy_over_idr: number | null;
  /** Flat rupiah off the shipping rate, capped at the rate itself. */
  subsidy_idr: number;
  delivery_estimate: string | null;
  is_active: boolean;
  sort_order: number;
}

export interface SiteSettings {
  id: boolean;
  hero_image: string | null;
  hero_title: string;
  hero_subtitle: string | null;
  hero_cta_label: string | null;
  hero_cta_href: string | null;
  banner_enabled: boolean;
  banner_image: string | null;
  banner_text: string | null;
  banner_link: string | null;
  homepage_category_ids: string[];
  featured_post_id: string | null;
  announcement_note: string | null;
  loyalty_rupiah_per_point: number;
  /** Every method the operator can pick from when marking an order paid, in
   *  the order they should appear in the dropdown. Free text -- whatever is
   *  in here is what the receipt will read. */
  payment_methods: string[];
  tier_silver_threshold: number;
  tier_gold_threshold: number;
  whatsapp_number: string | null;
  instagram_url: string | null;
  contact_email: string | null;
  seo_title: string;
  seo_description: string | null;
  og_image_url: string | null;
  /** Where parcels ship from. Only needed by live-rate couriers. */
  origin_contact_name: string | null;
  origin_phone: string | null;
  origin_address: string | null;
  origin_city: string | null;
  origin_province: string | null;
  origin_postal_code: string | null;
  origin_area_code: string | null;
  origin_note: string | null;
  /** Pre-launch page wording. Null means "use the built-in copy". */
  coming_soon_eyebrow: string | null;
  coming_soon_title: string | null;
  coming_soon_body: string | null;
  coming_soon_note: string | null;
  coming_soon_contact_line: string | null;
  /** Resend audience the mailing list is mirrored into. */
  resend_audience_id: string | null;
  /** How large a courier overcharge has to be before it is worth flagging. */
  courier_variance_alert_idr: number;
  updated_at: string;
}

export interface PaymentEvent {
  id: string;
  provider: string;
  external_id: string | null;
  amount_idr: number | null;
  status: string | null;
  matched_order_id: string | null;
  is_matched: boolean;
  is_resolved: boolean;
  payload: unknown;
  created_at: string;
}

export interface LoyaltyLedgerEntry {
  id: string;
  user_id: string;
  order_id: string | null;
  points: number;
  reason: string;
  created_by: string | null;
  created_at: string;
}
